name: Automated Unit Tests

# Triggers for the workflow
on: [push]
# on: 
#  push: 
#    branches: ["master"]
#  pull_request:
#    branches: ["master"]

# permissions required for Test reporting UI
permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write

jobs:
  backend-tests:
    name: Spring Boot Backend Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: 'maven'

      - name: Run Backend Unit Tests
#        working-directory: ./backend   would use if in the multi-module project
        run: mvn test

      # use this to show the test results at the bottom of the workflow run in GitHub actions
      - name: Publish Test Results GUI
        uses: EnricoMi/publish-unit-test-result-action@v2
        # always() allows test results to be published even when tests fail.
        if: always()
        with:
          files: "target/surefire-reports/*.xml"

      # Makes the coverage report from autoamated cloud runs on GitHub visible after run.
      - name: Upload Jacoco Coverage Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: jacoco-coverage-report
          path: "**/target/site/jacoco/"
